# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-minimal
url: http://single-cell.net

# Single-cell proteomics
title: SCP Meeting
description: Single-cell proteomics conferences in Boston


aux_links:
  "SCP center":
    - "http://center.single-cell.net"
  "Single-cell proteomics":
    - "https://web.northeastern.edu/slavovlab/blog/single-cell-proteomics/"    
  "Meetings":
    - "http://slavovlab.net/research.htm#Single-Cell-Proteomics-Conference"   

    

search_enabled: true


# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-4005755-4


plugins:
  - jekyll-seo-tag